### ISSUE TITLE
How to change the font and size?

### ISSUE THREAD

**Issue by Shougo** [dzhou121/gonvim#16]
I have executed `call rpcnotify(0, 'Gui', 'Font', 'Monospace:h13')`, but it was crashed.
I think it is bug.

**Comment by dzhou121** [comment]
I can't replicate it. What was the error when it crashed?

**Comment by Shougo** [comment]
OK.

```
Unhandle event update_sp
Unhandle event mode_info_set
Unhandle event update_sp
Unhandle event mode_info_set
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x80 addr=0x0 pc=0x7f08591007ed]

runtime stack:
runtime.throw(0xa317a0, 0x2a)
        /usr/lib/go-1.6/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
        /usr/lib/go-1.6/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 7 [syscall, locked to thread]:
runtime.cgocall(0x7cd8c0, 0xc82035da70, 0x0)
        /usr/lib/go-1.6/src/runtime/cgocall.go:123 +0x11b fp=0xc82035da20 sp=0xc82035d9f0
github.com/dzhou121/ui._Cfunc_newTextLayout(0x2602d20, 0x2454740, 0xbff0000000000000, 0x0)
        ??:0 +0x42 fp=0xc82035da70 sp=0xc82035da20
github.com/dzhou121/ui.NewTextLayout(0xc82040cc41, 0x1, 0xc8200300c0, 0xbff0000000000000, 0x1)
        /home/shougo/.go/src/github.com/dzhou121/ui/draw.go:794 +0xca fp=0xc82035dad0 sp=0xc82035da70
github.com/dzhou121/gonvim.drawText(0xc82040cb40, 0x1, 0x0, 0x31, 0x0, 0x0)
        /home/shougo/.go/src/github.com/dzhou121/gonvim/screen.go:529 +0x531 fp=0xc82035dc58 sp=0xc82035dad0
github.com/dzhou121/gonvim.(*Screen).Draw(0xc8200be500, 0xc8200bcc60, 0xc82040cb40)
        /home/shougo/.go/src/github.com/dzhou121/gonvim/screen.go:110 +0x330 fp=0xc82035dd60 sp=0xc82035dc58
github.com/dzhou121/ui.doAreaHandlerDraw(0x24b3770, 0x24f0fd0, 0x7ffd76335ad0)
        /home/shougo/.go/src/github.com/dzhou121/ui/areahandler.go:172 +0x166 fp=0xc82035ddb0 sp=0xc82035dd60
github.com/dzhou121/ui._cgoexpwrap_503c44ee75e0_doAreaHandlerDraw(0x24b3770, 0x24f0fd0, 0x7ffd76335ad0)
        ??:0 +0x35 fp=0xc82035ddd0 sp=0xc82035ddb0
runtime.call32(0x0, 0x7ffd763359d8, 0x7ffd76335a60, 0x18)
        /usr/lib/go-1.6/src/runtime/asm_amd64.s:472 +0x3e fp=0xc82035ddf8 sp=0xc82035ddd0
runtime.cgocallbackg1()
        /usr/lib/go-1.6/src/runtime/cgocall.go:267 +0x10c fp=0xc82035de30 sp=0xc82035ddf8
runtime.cgocallbackg()
        /usr/lib/go-1.6/src/runtime/cgocall.go:180 +0xd7 fp=0xc82035de90 sp=0xc82035de30
runtime.cgocallback_gofunc(0x411373, 0x7ce000, 0xc82035df00)
        /usr/lib/go-1.6/src/runtime/asm_amd64.s:716 +0x60 fp=0xc82035dea0 sp=0xc82035de90
runtime.asmcgocall(0x7ce000, 0xc82035df00)
        /usr/lib/go-1.6/src/runtime/asm_amd64.s:567 +0x42 fp=0xc82035dea8 sp=0xc82035dea0
runtime.cgocall(0x7ce000, 0xc82035df00, 0x0)
        /usr/lib/go-1.6/src/runtime/cgocall.go:124 +0x133 fp=0xc82035ded8 sp=0xc82035dea8
github.com/dzhou121/ui._Cfunc_uiMain()
        ??:0 +0x36 fp=0xc82035df00 sp=0xc82035ded8
github.com/dzhou121/ui.start(0xc82001a300, 0xa701e0)
        /home/shougo/.go/src/github.com/dzhou121/ui/main.go:56 +0x1f3 fp=0xc82035df80 sp=0xc82035df00
runtime.goexit()
        /usr/lib/go-1.6/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82035df88 sp=0xc82035df80
created by github.com/dzhou121/ui.Main
        /home/shougo/.go/src/github.com/dzhou121/ui/main.go:36 +0x6d

goroutine 1 [chan receive]:
github.com/dzhou121/ui.Main(0xa701e0, 0x0, 0x0)
        /home/shougo/.go/src/github.com/dzhou121/ui/main.go:37 +0x9d
main.main()
        /home/shougo/.go/src/github.com/dzhou121/gonvim/cmd/gonvim/gonvim.go:16 +0x3b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go-1.6/src/runtime/asm_amd64.s:1998 +0x1

goroutine 8 [syscall]:
syscall.Syscall(0x0, 0xc, 0xc82015c000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.6/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0xc, 0xc82015c000, 0x1000, 0x1000, 0x17, 0x0, 0x0)
        /usr/lib/go-1.6/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
syscall.Read(0xc, 0xc82015c000, 0x1000, 0x1000, 0xc8201678e0, 0x0, 0x0)
        /usr/lib/go-1.6/src/syscall/syscall_unix.go:161 +0x4d
os.(*File).read(0xc8200300a0, 0xc82015c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.6/src/os/file_unix.go:228 +0x53
os.(*File).Read(0xc8200300a0, 0xc82015c000, 0x1000, 0x1000, 0x4, 0x0, 0x0)
        /usr/lib/go-1.6/src/os/file.go:95 +0x8a
bufio.(*Reader).fill(0xc82001a5a0)
        /usr/lib/go-1.6/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadByte(0xc82001a5a0, 0xc82004dcb0, 0x0, 0x0)
        /usr/lib/go-1.6/src/bufio/bufio.go:229 +0x7a
github.com/neovim/go-client/msgpack.(*Decoder).Unpack(0xc820019130, 0x0, 0x0)
        /home/shougo/.go/src/github.com/neovim/go-client/msgpack/unpack.go:167 +0x73
github.com/neovim/go-client/msgpack/rpc.(*Endpoint).Serve(0xc8201029c0, 0x0, 0x0)
        /home/shougo/.go/src/github.com/neovim/go-client/msgpack/rpc/endpoint.go:384 +0x171
github.com/neovim/go-client/nvim.(*Nvim).Serve(0xc82015a450, 0x0, 0x0)
        /home/shougo/.go/src/github.com/neovim/go-client/nvim/nvim.go:53 +0x87
github.com/dzhou121/gonvim.InitEditor.func1(0xc82015a450)
        /home/shougo/.go/src/github.com/dzhou121/gonvim/editor.go:174 +0x33
created by github.com/dzhou121/gonvim.InitEditor
        /home/shougo/.go/src/github.com/dzhou121/gonvim/editor.go:179 +0xa66

goroutine 9 [semacquire]:
sync.runtime_Syncsemacquire(0xc820012f10)
        /usr/lib/go-1.6/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc820012f00)
        /usr/lib/go-1.6/src/sync/cond.go:63 +0x9b
github.com/neovim/go-client/msgpack/rpc.(*Endpoint).dequeueNotifications(0xc8201029c0, 0x0, 0x0, 0x0)
        /home/shougo/.go/src/github.com/neovim/go-client/msgpack/rpc/endpoint.go:645 +0x6b
github.com/neovim/go-client/msgpack/rpc.(*Endpoint).runNotifications(0xc8201029c0)
        /home/shougo/.go/src/github.com/neovim/go-client/msgpack/rpc/endpoint.go:657 +0x30
created by github.com/neovim/go-client/msgpack/rpc.(*Endpoint).Serve
        /home/shougo/.go/src/github.com/neovim/go-client/msgpack/rpc/endpoint.go:381 +0x15c

goroutine 34 [chan receive]:
github.com/dzhou121/gonvim.InitEditor.func2()
        /home/shougo/.go/src/github.com/dzhou121/gonvim/editor.go:198 +0x3f
created by github.com/dzhou121/gonvim.InitEditor
        /home/shougo/.go/src/github.com/dzhou121/gonvim/editor.go:200 +0xf0f

goroutine 196 [runnable, locked to thread]:
github.com/dzhou121/ui._Cfunc_freeDoubles(0x7f0834001fb0, 0x7f0834001d40)
        ??:0 +0x36
github.com/dzhou121/ui.(*TextLayout).Extents(0xc82027f8e0, 0x4024000000000000, 0x4034000000000000)
        /home/shougo/.go/src/github.com/dzhou121/ui/draw.go:837 +0xd7
github.com/dzhou121/gonvim.fontSize(0xc82027f8d8, 0x9, 0xd, 0xc82027f8d8)
        /home/shougo/.go/src/github.com/dzhou121/gonvim/font.go:34 +0x5e
github.com/dzhou121/gonvim.(*Font).change(0xc820012c00, 0xc820280f10, 0x9, 0xd)
        /home/shougo/.go/src/github.com/dzhou121/gonvim/font.go:59 +0x5d
github.com/dzhou121/gonvim.(*Editor).guiFont(0xc8200be700, 0xc820257ef8, 0x1, 0x1)
        /home/shougo/.go/src/github.com/dzhou121/gonvim/editor.go:333 +0x388
github.com/dzhou121/gonvim.(*Editor).handleRPCGui(0xc8200be700, 0xc8201673e0, 0x2, 0x2)
        /home/shougo/.go/src/github.com/dzhou121/gonvim/editor.go:218 +0x29c
created by github.com/dzhou121/gonvim.(*Editor).handleNotification.func1
        /home/shougo/.go/src/github.com/dzhou121/gonvim/editor.go:207 +0x52
```

**Comment by dzhou121** [comment]
What is your OS and version?

Also maybe worth to upgrade golang to the latest.

**Comment by Shougo** [comment]
```
go version
go version go1.6.2 linux/amd64
```

Ubuntu 16.04

This is old?

**Comment by dzhou121** [comment]
go1.6.2 is a bit old. The latest golang is 1.8.3

**Comment by dzhou121** [comment]
What is your gtk version?

**Comment by Shougo** [comment]
Thank you.  I have updated golang.
The crash is fixed.  But the font size is not changed.

**Comment by Shougo** [comment]
And `GuiFont Terminal` by `neovim-gui-shim` is crashed.

**Comment by dzhou121** [comment]
What is your gtk version?

**Comment by Shougo** [comment]
How to check the version?

**Comment by dzhou121** [comment]
try this ```apt list --installed | grep gtk```

**Comment by Shougo** [comment]
libgtk-3-0/xenial-updates,now 3.18.9-1ubuntu3.3 amd64 [インストール済み、自動]
libgtk-3-bin/xenial-updates,now 3.18.9-1ubuntu3.3 amd64 [インストール済み、自動]
libgtk-3-common/xenial-updates,xenial-updates,now 3.18.9-1ubuntu3.3 all [インストール済み、自動]
libgtk-3-dev/xenial-updates,now 3.18.9-1ubuntu3.3 amd64 [インストール済み]

**Comment by dzhou121** [comment]
Any updates on gtk?

**Comment by Shougo** [comment]
No

**Comment by Shougo** [comment]
I have changed the source code in editor.go.

Works: serif, monospace
Does not work: "Courier 10 Pitch"

**Comment by Shougo** [comment]
In ginit.vim `GuiFont Courier\ 10\ Pitch:h14` worked.

**Comment by Shougo** [comment]
`GuiFont Courier\ 10\ Pitch:h14` seems unstable.
Can you test it?

**Comment by dzhou121** [comment]
Just made some changes, can you please update to the latest and try again.

**Comment by Shougo** [comment]
I have updated it.  No change.

**Comment by dzhou121** [comment]
There was a bug in font rendering. Please update again.

**Comment by Shougo** [comment]
I have updated it, but no luck.

```vim
Unhandle event update_sp
Unhandle event mode_info_set
Unhandle event update_sp
Unhandle event mode_info_set
Unhandle event update_sp
Unhandle event mode_info_set
Unhandle event update_sp
Unhandle event mode_info_set
Unhandle event update_sp
Unhandle event mode_info_set
Unhandle event update_sp
Unhandle event mode_info_set
Unhandle event update_sp
Unhandle event mode_info_set
Unhandle event update_sp
Unhandle event mode_info_set
Unhandle event update_sp
Unhandle event mode_info_set
Unhandle event update_sp
Unhandle event mode_info_set
Unhandle event update_sp
....
```

The errors are displayed.

**Comment by Shougo** [comment]
gonvim is freezed after entering insert mode.

I use cursor shape feature.

```vim
" Use cursor shape feature
set guicursor=n-v-c:block-Cursor/lCursor-blinkon0,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor
```

**Comment by dzhou121** [comment]
Do you mean the same behavior as in #4

**Comment by Shougo** [comment]
It may be.
This is not occurred in the default font.

**Comment by dzhou121** [comment]
Can you please run go get -u github.com/dzhou121/gonvim/cmd/gonvim to update to latest gonvim and try again.

**Comment by Shougo** [comment]
Nice.  I will try it later.

**Comment by Shougo** [comment]
The problem is fixed!
Yey!
