### ISSUE TITLE
Error when running gonvim

### ISSUE THREAD

**Issue by boolow5** [dzhou121/gonvim#6]
Hi everyone, the first time I run `gonvim` the window was blank and if I press Enter I got this error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7963f9]

goroutine 19 [running, locked to thread]:
github.com/dzhou121/gonvim.(*AreaHandler).KeyEvent(0xc420150200, 0xc420128200, 0xc420126c00, 0xc420194000)
	/home/mahdi/src/src/github.com/dzhou121/gonvim/area.go:149 +0x109
github.com/dzhou121/ui.doAreaHandlerKeyEvent(0x1f44750, 0x1f40b10, 0x7ffc66e84cf0, 0xc400000008)
	/home/mahdi/src/src/github.com/dzhou121/ui/areahandler.go:263 +0x100
github.com/dzhou121/ui._cgoexpwrap_503c44ee75e0_doAreaHandlerKeyEvent(0x1f44750, 0x1f40b10, 0x7ffc66e84cf0, 0x1)
	github.com/dzhou121/ui/_obj/_cgo_gotypes.go:2458 +0x3f
github.com/dzhou121/ui._Cfunc_uiMain()
	github.com/dzhou121/ui/_obj/_cgo_gotypes.go:1842 +0x41
github.com/dzhou121/ui.start(0xc42013c120, 0x8c5330)
	/home/mahdi/src/src/github.com/dzhou121/ui/main.go:56 +0x196
created by github.com/dzhou121/ui.Main
	/home/mahdi/src/src/github.com/dzhou121/ui/main.go:36 +0x6b
```

**Comment by dzhou121** [comment]
Hi, can you please run ```go get -u github.com/dzhou121/gonvim/cmd/gonvim``` to update to the latest and try again.

**Comment by Alireza-Ta** [comment]
I have the problem too but updating changes nothing !

**Comment by dzhou121** [comment]
@Alireza-Ta Can you please post the error message?

**Comment by Alireza-Ta** [comment]
update it again and after running the gonvim, now it just pops up the app with a white screen and without any errors !

**Comment by dzhou121** [comment]
What is your os and version?

**Comment by Alireza-Ta** [comment]
MacOS Version 10.11.6

**Comment by dzhou121** [comment]
I only tested it on latest macOS 10.12.5 so not sure whether it works on older versions.

**Comment by dzhou121** [comment]
Please upgrade golang to latest and try again.
